// <auto-generated />
using System;
using Biosim.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Biosim.Migrations
{
    [DbContext(typeof(EFContext))]
    partial class EFContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Biosim.Models.CarnivoreModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int?>("CarnivoreID")
                        .HasColumnType("int");

                    b.Property<double>("Fitness")
                        .HasColumnType("float");

                    b.Property<int?>("HerbivoreID")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfBirths")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.ToTable("Carnivores");
                });

            modelBuilder.Entity("Biosim.Models.HerbivoreModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int?>("CarnivoreID")
                        .HasColumnType("int");

                    b.Property<double>("Fitness")
                        .HasColumnType("float");

                    b.Property<int?>("HerbivoreID")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfBirths")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.ToTable("Herbivores");
                });

            modelBuilder.Entity("Biosim.Models.ResultModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("CarnivoreAvgAge")
                        .HasColumnType("float");

                    b.Property<double>("CarnivoreAvgFitness")
                        .HasColumnType("float");

                    b.Property<double>("CarnivoreAvgWeight")
                        .HasColumnType("float");

                    b.Property<int>("CarnivoreBirths")
                        .HasColumnType("int");

                    b.Property<int>("Carnivores")
                        .HasColumnType("int");

                    b.Property<double>("HerbivoreAvgAge")
                        .HasColumnType("float");

                    b.Property<double>("HerbivoreAvgFitness")
                        .HasColumnType("float");

                    b.Property<double>("HerbivoreAvgWeight")
                        .HasColumnType("float");

                    b.Property<int>("HerbivoreBirths")
                        .HasColumnType("int");

                    b.Property<int>("Herbivores")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
